version: "3.7"

services:
  tic-tac-toe:
    container_name: tic-tac-toe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    stdin_open: true
